### ISSUE TITLE
Make CloudCustodian policies do an initial resource evaluation

### ISSUE THREAD

**Issue by Richard-Hansen** [ucsc-cgp/cgp-cloud-policies#26]
CloudCustodian policies do not do an initial evaluation of resources when deployed. We can create a second policy, this one will activate the policy when its created. A little hacky, but there don't seem to be other supported approaches.

```
policies:
  - name: trigger-config-eval
    resource: aws.config-rule
    filters:
      - ConfigRuleName: "my-config-rule"
    actions:
      - type: evaluate
```
